from __future__ import annotations

from typing import Protocol

from ..contracts.cases import CaseRecord, CaseTimeline
from ..contracts.common import TenantContext


class ClinicalControlCasePort(Protocol):
    def list_cases(self, ctx: TenantContext, limit: int) -> list[CaseRecord]: ...
    def get_case(self, case_id: int, ctx: TenantContext) -> CaseRecord: ...
    def get_timeline(self, case_id: int, ctx: TenantContext) -> CaseTimeline: ...
    def update_status(self, case_id: int, new_status: str, row_version: int, ctx: TenantContext) -> CaseRecord: ...
    def override_priority(self, case_id: int, new_score: int, reason: str, row_version: int, ctx: TenantContext) -> CaseRecord: ...
    def override_routing(self, case_id: int, new_category: str, reason: str, row_version: int, ctx: TenantContext) -> CaseRecord: ...
    def add_note(self, case_id: int, note: str, ctx: TenantContext) -> CaseTimeline: ...
